"""empty message

Revision ID: 081c363b4efe
Revises: 9059d7295902
Create Date: 2020-11-03 11:55:23.802008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081c363b4efe'
down_revision = '9059d7295902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('email', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'centers', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'centers', type_='unique')
    op.drop_column('centers', 'email')
    # ### end Alembic commands ###
