"""empty message

Revision ID: 0a3e0540dff6
Revises: 3f4bcd157b83
Create Date: 2020-11-10 10:37:20.490060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3e0540dff6'
down_revision = '3f4bcd157b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('probando', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centers', 'probando')
    # ### end Alembic commands ###
