"""empty message

Revision ID: 109d28779242
Revises: 4e47b30aee68
Create Date: 2020-11-13 08:53:49.029517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '109d28779242'
down_revision = '4e47b30aee68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centers', 'estado')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('estado', mysql.TINYINT(display_width=1),default=False, autoincrement=False, nullable=True))
    # ### end Alembic commands ###
