"""empty message

Revision ID: 136d03069acd
Revises: 271ff2e5213c
Create Date: 2020-11-03 19:08:35.280602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136d03069acd'
down_revision = '271ff2e5213c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('center_has_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('tipo_centro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['tipo_centro_id'], ['tipo_centro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('center_has_type')
    # ### end Alembic commands ###
