"""empty message

Revision ID: 23139cb139ac
Revises: 312c32ddd0a3
Create Date: 2020-11-12 14:26:17.848431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23139cb139ac'
down_revision = '312c32ddd0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='centers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'centers', ['email'], unique=True)
    # ### end Alembic commands ###
