"""empty message

Revision ID: 3f4bcd157b83
Revises: a5df62950d34
Create Date: 2020-11-10 09:47:22.552907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f4bcd157b83'
down_revision = 'a5df62950d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('longitud', sa.Float(), nullable=False))
    op.add_column('centers', sa.Column('latitud', sa.Float(), nullable=False))
    op.drop_column('centers', 'coordenadas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('coordenadas', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('centers', 'latitud')
    op.drop_column('centers', 'longitud')
    # ### end Alembic commands ###
