"""empty message

Revision ID: 404a769295e5
Revises: 52f648f0004e
Create Date: 2020-11-03 13:58:19.887799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '404a769295e5'
down_revision = '52f648f0004e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centers', 'hora_cierre')
    op.drop_column('centers', 'PRUEBA')
    op.drop_column('centers', 'hora_apertura')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('hora_apertura', mysql.DATETIME(), nullable=False))
    op.add_column('centers', sa.Column('PRUEBA', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('centers', sa.Column('hora_cierre', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
