"""empty message

Revision ID: 40ec813a5cdf
Revises: 081c363b4efe
Create Date: 2020-11-03 13:48:24.754554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40ec813a5cdf'
down_revision = '081c363b4efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('centers', 'municipio',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('centers', 'tipo_centro',
               existing_type=mysql.ENUM('1', '2'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('centers', 'tipo_centro',
               existing_type=mysql.ENUM('1', '2'),
               nullable=False)
    op.alter_column('centers', 'municipio',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
