"""empty message

Revision ID: 52f648f0004e
Revises: 40ec813a5cdf
Create Date: 2020-11-03 13:56:29.461280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f648f0004e'
down_revision = '40ec813a5cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('PRUEBA', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centers', 'PRUEBA')
    # ### end Alembic commands ###
