"""empty message

Revision ID: 5c71a59fe470
Revises: fa4044ba1f14
Create Date: 2020-11-03 10:15:40.880380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c71a59fe470'
down_revision = 'fa4044ba1f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('center_has_type')
    op.drop_index('id', table_name='tipo_centro')
    op.drop_index('ix_tipo_centro_nombre', table_name='tipo_centro')
    op.drop_table('tipo_centro')
    op.add_column('centers', sa.Column('tipo_centro', sa.Enum('1', '2'), nullable=True))
    op.drop_column('centers', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('gender', mysql.ENUM('M', 'F'), nullable=True))
    op.drop_column('centers', 'tipo_centro')
    op.create_table('tipo_centro',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_tipo_centro_nombre', 'tipo_centro', ['nombre'], unique=False)
    op.create_index('id', 'tipo_centro', ['id'], unique=True)
    op.create_table('center_has_type',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('center_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tipo_centro_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], name='center_has_type_ibfk_1'),
    sa.ForeignKeyConstraint(['tipo_centro_id'], ['tipo_centro.id'], name='center_has_type_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
