"""empty message

Revision ID: 6232673ba35f
Revises: e87605c30690
Create Date: 2020-10-16 14:27:06.722006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6232673ba35f'
down_revision = 'e87605c30690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('mail', sa.String(length=30), nullable=True),
    sa.Column('cant_elem', sa.Integer(), nullable=True),
    sa.Column('habilitado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configs')
    # ### end Alembic commands ###
