"""empty message

Revision ID: 984e2acf68a6
Revises: 89f7afe63ea8
Create Date: 2020-11-02 22:43:22.909403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984e2acf68a6'
down_revision = '89f7afe63ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('direccion', sa.String(length=30), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('hora_apertura', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hora_cierre', sa.DateTime(timezone=True), nullable=False),
    sa.Column('web', sa.String(length=30), nullable=True),
    sa.Column('publicado', sa.Boolean(), nullable=True),
    sa.Column('protocolo_vista', sa.String(length=30), nullable=True),
    sa.Column('coordenadas', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_centers_nombre'), 'centers', ['nombre'], unique=False)
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_municipios_nombre'), 'municipios', ['nombre'], unique=False)
    op.create_table('tipo_centro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_tipo_centro_nombre'), 'tipo_centro', ['nombre'], unique=False)
    op.create_table('center_has_municipio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('center_has_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('tipo_centro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.ForeignKeyConstraint(['tipo_centro_id'], ['tipo_centro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('center_has_type')
    op.drop_table('center_has_municipio')
    op.drop_index(op.f('ix_tipo_centro_nombre'), table_name='tipo_centro')
    op.drop_table('tipo_centro')
    op.drop_index(op.f('ix_municipios_nombre'), table_name='municipios')
    op.drop_table('municipios')
    op.drop_index(op.f('ix_centers_nombre'), table_name='centers')
    op.drop_table('centers')
    # ### end Alembic commands ###
