"""empty message

Revision ID: a5df62950d34
Revises: e46da3d701a2
Create Date: 2020-11-05 16:49:05.718093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5df62950d34'
down_revision = 'e46da3d701a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('estado', sa.Boolean(), nullable=True))
    op.drop_column('centers', 'publicado')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('publicado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('centers', 'estado')
    # ### end Alembic commands ###
