"""empty message

Revision ID: a6dc1a1ce487
Revises: 0a3e0540dff6
Create Date: 2020-11-10 10:37:32.633441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6dc1a1ce487'
down_revision = '0a3e0540dff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centers', 'probando')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('probando', mysql.FLOAT(), nullable=False))
    # ### end Alembic commands ###
