"""empty message

Revision ID: e804e32d5a6d
Revises: 23139cb139ac
Create Date: 2020-11-12 15:20:56.941398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e804e32d5a6d'
down_revision = '23139cb139ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('centers', 'latitud',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('centers', 'longitud',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('centers', 'longitud',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('centers', 'latitud',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
