"""empty message

Revision ID: f0a8257da5d4
Revises: 109d28779242
Create Date: 2020-11-13 09:00:30.060177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a8257da5d4'
down_revision = '109d28779242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centers', sa.Column('estado', sa.Boolean(), nullable=True,default=None))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centers', 'estado')
    # ### end Alembic commands ###
