"""empty message

Revision ID: fbf19301ef9f
Revises: 99080fd15c6f
Create Date: 2020-10-12 10:51:53.532115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf19301ef9f'
down_revision = '99080fd15c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'id', nullable=False, autoincrement=True, existing_type=sa.INTEGER)
    op.alter_column('users', 'id', nullable=False, autoincrement=True, existing_type=sa.INTEGER)
    op.alter_column('issues', 'id', nullable=False, autoincrement=True, existing_type=sa.INTEGER)
    op.alter_column('statuses', 'id', nullable=False, autoincrement=True, existing_type=sa.INTEGER)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'id', nullable=False, autoincrement=False, existing_type=sa.INTEGER)
    op.alter_column('users', 'id', nullable=False, autoincrement=False, existing_type=sa.INTEGER)
    op.alter_column('issues', 'id', nullable=False, autoincrement=False, existing_type=sa.INTEGER)
    op.alter_column('statuses', 'id', nullable=False, autoincrement=False, existing_type=sa.INTEGER)
    # ### end Alembic commands ###
